config/routes.rb
Rails.application.routes.draw do
  root 'users#home'
  resources :users do
    collection do
      get :show_users
    end
  end
  resources :roles do
    collection do
        post :hide_roles
        post :update_roles
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
class Role < ApplicationRecord
  has_many :user_roles
  has_many :users, through: :user_roles
    scope :active, -> { where(active: true) }
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email = email.downcase }
    validates :email, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }

  # has_one :role, :class_name => "Role", :foreign_key => 'role_id', :validate => true
  has_many :user_roles
  has_many :roles, through: :user_roles
  has_attached_file :avatar, 
  :path => ":rails_root/public/system/:attachment/:id/:basename_:style.:extension",
  :url => "/system/:attachment/:id/:basename_:style.:extension",
  :styles => {
    :thumb    => ['100x100#',  :jpg, :quality => 70],
    :preview  => ['480x480#',  :jpg, :quality => 70],
    :large    => ['600>',      :jpg, :quality => 70],
    :retina   => ['1200>',     :jpg, :quality => 30]
  },
  :convert_options => {
    :thumb    => '-set colorspace sRGB -strip',
    :preview  => '-set colorspace sRGB -strip',
    :large    => '-set colorspace sRGB -strip',
    :retina   => '-set colorspace sRGB -strip -sharpen 0x0.5'
  }
  validates_attachment :avatar,
  :presence => true,
  :size => { :in => 0..10.megabytes },
  :content_type => { :content_type => /^image\/(jpeg|png|gif|tiff)$/ }

end

app/models/user_role.rb
class UserRole < ApplicationRecord
	belongs_to :role
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/roles_controller.rb
class RolesController < ApplicationController
  def new
    @role = Role.new
  end

  def create
    @role = Role.new(role_params) 
    if @role.save
      flash[:success] = "Role successfully created"
      redirect_to @role
      # Handle a successful save.
    else
      render 'new'
    end
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @roles = Role.all
  end

  def hide_roles
  end

  def update_roles
    if params[:role][:name].present?
      Role.where(:id=>params["role"]["name"].collect(&:to_i)).each do |a|
        a.update_attribute(:active, false)
      end
      flash[:success] = "Role successfully updated"
    end
    redirect_to roles_url
  end

  def show
    @role = Role.find(params[:id])
  end

  private

  def role_params
    params.require(:role).permit(:name, :active)      
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      params["user"]["user_roles"].collect(&:to_i).each do |i|
        if i != 0
          @user.roles << Role.where(id: i).first
        end
      end
      flash[:success] = "User successfully created"
      redirect_to @user
      # Handle a successful save.
    else
      render 'new'
    end
  end

  def update
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
  end

  def index
    @users = User.joins(:roles).where("roles.active = ?", true).distinct.paginate(page: params[:page], per_page: 3)
    respond_to do |format|
      format.html
      format.js
    end
    # render json: {content: render_to_string(partial: 'view',
    #                                      formats: [:html],
    #                                      layout: false,
    #                                      locals: { users: @users }) }
  end

  def show_users
    @users = User.joins(:roles).where("roles.active = ?", true).distinct.paginate(page: params[:page], per_page: 3)
    respond_to do |format|
      format.js
    end
  end

  def show
    @user = User.find(params[:id])

  end

  def home
  end

  private

  def user_params
    params.require(:user).permit(:firstname, :email, :lastname, :role_id, :avatar)
      
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.firstname, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LotVueAssignment</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/roles/create.html.erb
<h1>Roles#create</h1>
<p>Find me in app/views/roles/create.html.erb</p>

app/views/roles/destroy.html.erb
<h1>Roles#destroy</h1>
<p>Find me in app/views/roles/destroy.html.erb</p>

app/views/roles/edit.html.erb
<h1>Roles#edit</h1>
<p>Find me in app/views/roles/edit.html.erb</p>

app/views/roles/hide_roles.html.erb
<%= form_for(Role.new, url: update_roles_roles_path )do |f| %>
<% Role.all.each do |a| %>
    <%= f.label :name, a.name%>
    <%= f.check_box(:name, { :multiple => true, checked: !a.active }, a.id, false)%>



<% end %>
<%= f.submit "update", class: "btn btn-primary" %>
<% end %>

app/views/roles/index.html.erb
<table class="table table-bordered" id="roles_list"data-sort-name="name" data-sort-order="desc" style="width: 60%;">
  <thead>
    <tr>
      <th data-field="name" data-sortable="true">Name</th>
    </tr>
  </thead>

  <tbody>
    <% @roles.each do |role| %>
      <tr>
        <td ><%= role.name %></td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/roles/new.html.erb
<h1 style="text-align: center;">Create a Role</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@role) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
      <%= f.hidden_field :active, :value => true %>
      <br>


      <%= f.submit "Create a role", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/roles/show.html.erb
<%= @role.name %>

app/views/roles/update.html.erb
<h1>Roles#update</h1>
<p>Find me in app/views/roles/update.html.erb</p>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/_view.html.erb
<% @users.each do |user| %>
  <tr>
    <td ><%= user.firstname %> <%= user.lastname %></td>
    
    <td><%= user.email  %> </td>
    
    <td> <%= user.roles.active.pluck(:name).join(",") %> </td>
  </tr>
<%end%>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Edit a user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="field">
        <%= f.label :firstname %>
        <%= f.text_field :firstname, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :lastname %>
        <%= f.text_field :lastname, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :avatar %><br>
        <%= f.file_field :avatar %>
      </div>
      <div class="field">
        <%= f.collection_select :user_roles, Role.active, :id, :name, {},{multiple: true} %>
      </div>
      <%= f.submit "Edit a user", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/home.html.erb
<head>
  <script type="text/javascript">

  </script>
</head>
<h2>User Role App</h2>
<%= link_to '<button type="button">Create Roles</button>'.html_safe, new_role_path %>
<%= link_to '<button type="button">Create User</button>'.html_safe, new_user_path %>
<%= link_to 'show users', show_users_users_path, id: 'button', method: :get, remote: true %>
<%= link_to '<button type="button">Hide roles</button>'.html_safe, hide_roles_roles_path, :method => :post %>
<div id="show_users"></div>

app/views/users/index.html.erb
<%= will_paginate @users %>
<table class="table table-bordered" id="users_list"data-sort-name="name" data-sort-order="desc" style="width: 60%;">
  <thead>
    <tr>
      <th data-field="name" data-sortable="true">Name</th>
      <th data-field="email" data-sortable="true">Email</th>
      <th data-field="roles" data-sortable="true">Roles</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td ><%= user.firstname %> <%= user.lastname %></td>
        
        <td><%= user.email  %> </td>
        
        <td> <%= user.roles.active.pluck(:name).join(",") %> </td>
      </tr>
    <%end%>
  </tbody>
</table>
<%= will_paginate @users %>

app/views/users/new.html.erb
<h1 style="text-align: center;">Create a user</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>
      <div class="field">
        <%= f.label :firstname %>
        <%= f.text_field :firstname, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :lastname %>
        <%= f.text_field :lastname, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>
      <div class="field">
        <%= f.label :avatar %><br>
        <%= f.file_field :avatar %>
      </div>
      <div class="field">
        <%= f.collection_select :user_roles, Role.active, :id, :name, {},{multiple: true} %>
      </div>
      <%= f.submit "Create a user", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<h1>
  <%= (@user.firstname + " " + @user.lastname) %>
</h1>
 <%= @user.email %>
<p>
    <strong>Avatar:</strong>
    <%= image_tag @user.avatar.url(:large) %>
</p>

app/views/users/show_users.js.erb
$('#show_users').html("<%= escape_javascript(render('view')) %>");

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>